---
# the host in which the playbook will be run
- hosts: localhost
  # in this example, we using a localhost, so this is needed
  connection: local

  # the target user Ansible will impersonate when provisioning
  user: pantasio

  # this makes all tasks run with sudo by default
  sudo: true

  # additional variables
  vars:
    user: pantasio

  # roles are a way to group tasks; they will run in the sequence determined here
  roles:
#    - { role: pantasio.fish, fish_users: ['pantasio', 'vagrant'], fish_completions: ['composer'] }
    - { role: pantasio.fish, fish_users: ['pantasio'], fish_completions: ['composer'] }
