---

- name: Add repository source
  apt_repository:
    repo: "deb http://download.opensuse.org/repositories/shells:/fish:/release:/2/Debian_{{ ansible_lsb.major_release|int }}.0/ /"
    state: present
